spring.application.name=E-Learning


spring.datasource.url=jdbc:mysql://localhost:3306/ELearning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Vivek@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=admin
spring.security.user.password=vivek

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

logging.level.org.springframework=INFO

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379



# Session store type
spring.session.store-type=redis

# Optional: Session timeout (in seconds)
server.servlet.session.timeout=6000

# Optional: Redis namespace for sessions
spring.session.redis.namespace=spring:session
