spring.application.name=E-Learning

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ELearning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vivek@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:vivek}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=${SERVER_PORT:8080}

logging.level.org.springframework=INFO

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.session.store-type=redis
server.servlet.session.timeout=6000
spring.session.redis.namespace=spring:session

app.upload.dir=${APP_UPLOAD_DIR:uploads}
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
